name: NPM Dependency Manager For Your GitHub Organization
description: This action handles automated update of dependencies in package.json between projects from the same GitHub organization.
inputs:
  custom_id:
    description: >
      This custom_id is added as a unique identifier value to the PR created by the bot so the bot can later recognize it as created by the bot, so it updates existing PR instead creating new one.
      If custom_id is not specified, action assumes that you still want bot to create multiple PRs in one repo, with multiple updates. Once you add the custom_id, you enable flow with active one PR per repo.
    required: false
  github_token:
    description: >
      Token to use GitHub API. It must have "repo" scopes so it can push to repos.
      It cannot be the default GitHub Actions token GITHUB_TOKEN. GitHub Action token's permissions are limited to the repository that contains your workflows.
      Provide token of the user that has rights to push to the repos that this action is suppose to update. 
    required: true
  committer_username:
    description: >
      The username (not display name) of the committer that will be used in the commit of changes in the workflow file in specific repository.
      In the format `web-flow`.
    default: web-flow
    required: false
  committer_email:
    description: >
      The email of the committer that will be used in the commit of changes in the workflow file in specific repository.
      In the format `noreply@github.com`.
    default: noreply@github.com
    required: false
  commit_message_prod:
    description: >
      It is used as a commit message when bumping dependency from "dependencies" section in package.json. 
      In case dependency is located in both dependencies and devDependencies of dependant, then prod commit message is used.
      It is also used as a title of the pull request that is created by this action.
    required: false
  commit_message_dev:
    description: >
      It is used as a commit message when bumping dependency from "devDependencies" section in package.json. 
      It is also used as a title of the pull request that is created by this action.
    required: false
  packagejson_path:
    description: >
      Path to package.json file if not located in the root of the project. Provide just the path without file name. In the format: `./nested/location`.
    default: ./
    required: false
  repos_to_ignore:
    description: >
      Comma-separated list of repositories that should not get updates from this action.
      Action already ignores the repo in which the action is triggered so you do not need to add it explicitly.
      In the format: `repo1,repo2`.
    required: false
  base_branch:
    description: >
      Name of the base branch, where changes in package.json must be applied. It is used in PR creation. If not provided, default branch is used
      In the format: `next-major`.
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: chevrons-up
  color: gray-dark
